### ISSUE TITLE
colour gene label by novelty

### ISSUE THREAD

**Issue by rimamust** [mkanai/fujiplot#11]
Hi,

Is there a quick way to change the label color by its novelty (known vs novel)?

Thanks
Rima

**Comment by mkanai** [comment]
Hi Rima,

You can tweak an intermediate file `data_tracks/label.txt` and add the fifth column with `color=<custom_color_name>`. You can modify a custom color name by modifying `config/color.conf`.

These intermediate files are automatically deleted by default. Please comment out this line to keep them.
https://github.com/mkanai/fujiplot/blob/master/fujiplot.R#L197-L207
