### ISSUE TITLE
error

### ISSUE THREAD

**Issue by MinjaYuan** [mkanai/fujiplot#12]
Dear author, when I was reproducing your diagram with linux, this kind of situation would occur, which did not stop, and then the following error would appear when I canceled the task. Is it the problem of infinite loop you said? Do you need to download a patch? Thank you very much!!!!

.....
debuggroup summary 5.14s ... see progress with -debug_group text
debuggroup summary 5.14s ... see placement summary with -debug_group textplace
....

mv: cannot stat ‘/home/circos-0.69-9/fujiplot-master/output/circos.png’: No such file or directory
Error in cairo_pdf(file.path(output_dir, "barplot.pdf"), width = 8, height = 8,  :
  cairo_pdf: Cairo-based devices are not available for this platform
Execution halted

**Comment by mkanai** [comment]
Hi, thanks for reaching out. Yes, this is a known issue of circos -- please apply [our patch](https://gist.github.com/mkanai/be05f40f933112bfb70bb08076cdaa00) to your circos or use our patched version [here](https://www.dropbox.com/s/z6jdwhj0o570fp8/circos-0.69-6-kanai.tgz?dl=0).
