### ISSUE TITLE
Problem with the output figure....

### ISSUE THREAD

**Issue by MuBulut** [mkanai/fujiplot#5]
Hi, 
I wanted to run now the script with my dataset, and this type of error occurs.....

![image](https://user-images.githubusercontent.com/67698282/90757389-da84af80-e2dd-11ea-8db6-94891bb85b31.png)

The output seems empty, are there any limitations with the numbers of traits, since I have 920 traits...

My Trait list looks like this:

[I have in total two categories ..._BASE and .....GROUP]

My input file look like this:

[The trait is basically a mass feature of an unknown compound and the Gene is the same as the Locus ID since I do not have information of the gene in those regions]

EDIT:
Found the problem most likely....

![image](https://user-images.githubusercontent.com/67698282/90806106-daf06b00-e31c-11ea-9002-92cf60dd811b.png)

Is there a way to increase the highlighted data points?

EDIT:

![image](https://user-images.githubusercontent.com/67698282/90806251-0c693680-e31d-11ea-82b9-62199c604662.png)

Changed it in the housekeeping.config file accordingly [=2.991.000 to be sure], but still indicates that I need to change the threshold from 25.000 up to atleast 29.910.....

Thanks.
Mustafa

**Comment by mkanai** [comment]
Hi, thanks for reaching out and apologies for the delay in getting back to you. I'm not sure why `housekeeping.conf` doesn't take effect... Would you mind testing whether the script works with a smaller input file?

I wonder, even when `housekeeping.conf`  works, the output might become too dense with 29910 points, though...

**Comment by MuBulut** [comment]
Ok, now I got an output by reducing the files to 24.949 points.
You are right it is way to dense.....
I think I will perform further filtering before performing the script.
At least now the script works for my data.
Thanks

**Comment by mkanai** [comment]
Great! Please let me know if you have any other questions.

Thanks,
Masa
