### ISSUE TITLE
Adding more categories/Colors

### ISSUE THREAD

**Issue by MuBulut** [mkanai/fujiplot#6]
Hi again,
I wanted to create more then 9 categories, however I was not sure where to get the color codes for more colors then the defined 9 in your example files, to generate more categories.
Thanks in advance.
Mustafa

EDIT:
found out that it is HEX based, should work now I guess.

**Comment by mkanai** [comment]
Cool! Yes, you can define any color as in `traitlist.txt`.
https://github.com/mkanai/fujiplot/blob/master/input_example/traitlist.txt
