### ISSUE TITLE
Circos vs circlize 

### ISSUE THREAD

**Issue by liutiming** [mkanai/fujiplot#8]
Thanks for the awesome package!

As a design question, I wonder why you chose circos and not [circlize](https://github.com/jokergoo/circlize)? Was there additional functionality required in circos?

**Comment by mkanai** [comment]
Hi @liutiming,

Thanks for your interest! Re: your question, I wasn't familiar with circlize when I started the development -- please feel free to make a PR if you come up with more seamless integration using circlize.

Best,
Masa
