### ISSUE TITLE
output_example svg image is empty 

### ISSUE THREAD

**Issue by anbai106** [mkanai/fujiplot#9]
Hi,

Thank you for this beautiful visualization! I successfully ran your example after struggling to install Circos on my Mac, but the output images for SVG format are empty.

Do you have a fix for this?

<img width="1061" alt="Screenshot 2023-06-25 at 9 05 06 AM" src="https://github.com/mkanai/fujiplot/assets/16743978/cdb3bf96-cdc1-4ac5-b166-265b03ac2925">

Also, the barplot's color is not correct - black and white...

[barplot.pdf](https://github.com/mkanai/fujiplot/files/11859761/barplot.pdf)

The output log for running the script is here:

> *********************************************************************
> * Fuji plot -- a circos representation of multiple GWAS results
> * Version 1.0.3
> * Masahiro Kanai (mkanai@g.harvard.edu)
> * Harvard Medical School / RIKEN IMS / Osaka Univerisity
> * GNU General Public License v3
> *********************************************************************
> Loading input files...
> * Input data: /Users/username/Project/fujiplot/input_example/input.txt
> * Number of significant SNPs: 1407
> * Number of unique loci: 763
> 
> * Trait list: /Users/username/Project/fujiplot/input_example/traitlist.txt
> * Number of traits: 58 (TC,HDL-C,LDL-C,TG,BS,HbA1c,TP,Alb,NAP,AG,BUN,sCr,eGFR,UA,Na,K,Cl,Ca,P,TBil,ZTT,AST,ALT,ALP,GGT,APTT,PT,Fbg,CK,LDH,CRP,WBC,Neutro,Eosino,Baso,Mono,Lym,RBC,Hb,Ht,MCV,MCH,MCHC,Plt,SBP,DBP,MAP,PP,IVS,PW,LVDd,LVDs,LVM,LVMI,RWT,FS,EF,EA)
> * Number of categories: 9 (Metabolic,Protein,Kidney-related,Electrolyte,Liver-related,Other biochemical,Hematological,Blood pressure,Echocardiographic)
> 
> * Output dir: /Users/username/Project/fujiplot/output_example
> 
> Excluded 5 traits because of no significant SNPs (IVS,PW,LVM,LVMI,EA).
> 
> Generating configuration and data files for circos...
> * Color configuration: /Users/username/Project/fujiplot/config/color.conf
> * Scatter background configuration: /Users/username/Project/fujiplot/config/scatter_background.conf
> * Highlights data (inter-categorical pleiotropic loci): /Users/username/Project/fujiplot/data_tracks/highlights.txt
> * Scatter plot data (significant loci): /Users/username/Project/fujiplot/data_tracks/scatter.txt
> * Stacked bar plot data (# significant SNPs per locus): /Users/username/Project/fujiplot/data_tracks/stacked.txt
> * Label data (name of inter-categorical pleiotropic loci): /Users/username/Project/fujiplot/data_tracks/label.txt
> 
> Calling circos to plot...
> * Call: circos -conf /Users/username/Project/fujiplot/config/circos.conf -debug_group summary
> 
> debuggroup summary 0.07s welcome to circos v0.69-6 31 July 2017 on Perl 5.030003
> debuggroup summary 0.08s current working directory /Users/username/Project/fujiplot
> debuggroup summary 0.08s command /Users/username/Software/circos-0.69-6-kanai/bin/circos -conf /Users/username/Project/fujiplot/config/circos.conf -debug_group summary
> debuggroup summary 0.08s loading configuration from file /Users/username/Project/fujiplot/config/circos.conf
> debuggroup summary 0.08s found conf file /Users/username/Project/fujiplot/config/circos.conf
> debuggroup summary 0.13s debug will appear for these features: summary
> debuggroup summary 0.13s bitmap output image ./output/circos.png
> debuggroup summary 0.13s SVG output image ./output/circos.svg
> debuggroup summary 0.13s parsing karyotype and organizing ideograms
> debuggroup summary 0.16s karyotype has 24 chromosomes of total size 3,095,677,436
> debuggroup summary 0.16s applying global and local scaling
> debuggroup summary 0.16s allocating image, colors and brushes
> 
>   *** CIRCOS ERROR ***
> 
>       cwd: /Users/username/Project/fujiplot
> 
>       command: /Users/username/Software/circos-0.69-6-kanai/bin/circos -conf
>       /Users/username/Project/fujiplot/config/circos.conf -debug_group summary
> 
>   There was a problem with True Type font support. Circos could not render text
>   from the font file
> 
>       /Users/username/Software/circos-0.69-6-kanai/bin/../fonts/modern/cmuntt.ttf
> 
>   Please check that gd (system graphics library) and GD (Perl's interface to gd)
>   are compiled with True Type support.
> 
>   On UNIX systems, try
> 
>       gdlib-config --all
> 
>   and look for GD_FREETYPE in the 'features' line and -lfreetype in the 'libs'
>   line. If these are there, it's likely that your Perl GD module needs
>   recompiling.
> 
>   For help in installing libgd and/or GD, see
> 
>       http://www.perlmonks.org/?node_id=621579
> 
>   If you are having trouble debugging this error, first read the best practices
>   tutorial for helpful tips that address many common problems
> 
>       http://www.circos.ca/documentation/tutorials/reference/best_practices
> 
>   The debugging facility is helpful to figure out what's happening under the
>   hood
> 
>       http://www.circos.ca/documentation/tutorials/configuration/debugging
> 
>   If you're still stumped, get support in the Circos Google Group.
> 
>       http://groups.google.com/group/circos-data-visualization
> 
>   Please include this error, all your configuration, data files and the version
>   of Circos you're running (circos -v).Do not email me directly -- please use
>   the group.
> 
>   Stack trace:
>  at /Users/username/Software/circos-0.69-6-kanai/bin/../lib/Circos/Error.pm line 425.
> 	Circos::Error::fatal_error("font", "no_ttf", "/Users/username/Software/circos-0.69-6-kanai/bin/../fonts/modern/c"...) called at /Users/username/Software/circos-0.69-6-kanai/bin/../lib/Circos/Font.pm line 192
> 	Circos::Font::get_label_size("font_file", "/Users/username/Software/circos-0.69-6-kanai/bin/../fonts/modern/c"..., "size", 10, "text", "abc123") called at /Users/username/Software/circos-0.69-6-kanai/bin/../lib/Circos/Font.pm line 243
> 	Circos::Font::sanity_check() called at /Users/username/Software/circos-0.69-6-kanai/bin/../lib/Circos.pm line 726
> 	Circos::run("Circos", "debug_group", "summary", "_cwd", "/Users/username/Project/fujiplot", "configfile", "/Users/username/Project/fujiplot/config/circos.conf", "_argv", ...) called at /Users/username/Software/circos-0.69-6-kanai/bin/circos line 536
> mv: /Users/username/Project/fujiplot/output/circos.png: No such file or directory
> 
> * Final circos outputs: /Users/username/Project/fujiplot/output_example/circos.{png,svg}.

I know that i can debug into the script `fujiplot.R`, but if you can quickly spot the issue. It would be greatly appreciated!

Thanks

**Comment by mkanai** [comment]
Hi, can you take a look at the error messages under `*** CIRCOS ERROR ***`? Many thanks!

**Comment by anbai106** [comment]
Yes, I found that it was because of some incompatibility of some library for Circos -- very annoying to install it to be honest. I will try it on my Linux machine.

Thanks

**Comment by mkanai** [comment]
I'm going to close this due to inactivity. Please let me know if your issue persists.
